name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CICD:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Print current directory
      run: pwd
    - name: List directory contents
      run: ls -R

    ## Create YML
    - name : Create application-secret.yml File
      run : |
        echo "${{secrets.APPLICATION_SECRET_YML}}" > songgpt/src/main/resources/application-secret.yml
        find songgpt/src
    - name : Create application-API-KEY.yml File
      run : |
        echo "${{secrets.APPLICATION_API_KEY_YML}}" > songgpt/src/main/resources/application-API-KEY.yml
        find songgpt/src
    - name : Create application-aws.yml File
      run : |
        echo "${{secrets.APPLICATION_AWS_YML}}" > songgpt/src/main/resources/application-aws.yml
        find songgpt/src
        
    ## Permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x songgpt/gradlew
      shell: bash
      
    ## Build Gradle
    - name: Build with Gradle  
      run: |
        cd songgpt
        ./gradlew build

    ## Build and Push to Docker Hub
    - name: Docker build & push to Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
        docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/{{ secrets.DOCKER_REPO }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/{{ secrets.DOCKER_REPO }}
      
    ## Deploy EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
              sudo docker rm -f $(sudo docker ps -qa) # Remove all running containers
              sudo docker pull ${{ secrets.DOCKER_USERNAME }}/{{ secrets.DOCKER_REPO }}
              sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/{{ secrets.DOCKER_REPO }}
